### ISSUE TITLE
Duplicated HelloWorld files

### ISSUE THREAD

**Issue by lexandro** [msteinhoff/hello-world#1]
Dear Creator of this beautiful application,

I noticed there are two HelloWorld.java are provided and I have no idea what is the real one. Could you clarify it please?

<grin>

**Comment by msteinhoff** [comment]
Thanks for your interest in my hello-world application.

The `HelloWorld.java` file in src/main/java seems to be an error, only the one in the `de.helloworld` package should be used.

You can send a pull request if you want.

**Comment by msteinhoff** [comment]
Fixed by #2
